save_path: results/point6/
model:
    name: AlexNet_DAG_SVM_RBF
    kernel: rbf
    mode: DAG


training:
    B: 32



data:
    transformations:
        train:
            -   types:  torchvision.transforms.Resize
                params: {'size': [256, 256]}
            -   types:  torchvision.transforms.RandomCrop
                params: {'size': [224, 224]}
        test:
            -   types:  torchvision.transforms.Resize
                params: {'size': [224, 224]}
        normalization:
            -   types:  torchvision.transforms.Normalize
                params: {'mean': [0.485, 0.456, 0.406], 
                         'std':  [0.229, 0.224, 0.225]}

