save_path: results/point2/
model:
    name: "CNN_2d"
    nn_config: |
        conv2d      channels: ->8   kernel_size: (3, 3)  stride: (1, 1) padding: (1, 1)
        batchnorm2d num_features: 8
        relu
        conv2d      channels: ->8   kernel_size: (3, 3)  stride: (1, 1)
        batchnorm2d num_features: 8
        relu 
        maxpool2d                   kernel_size: (2, 2)  stride: (2, 2)

        conv2d      channels: ->16  kernel_size: (5, 5)  stride: (1, 1)  padding: (1, 1)
        batchnorm2d num_features: 16
        relu
        conv2d      channels: ->16  kernel_size: (5, 5)  stride: (1, 1) 
        batchnorm2d num_features: 16
        relu 
        maxpool2d                   kernel_size: (2, 2)  stride: (2, 2)

        conv2d      channels: ->32  kernel_size: (7, 7)  stride: (1, 1)
        batchnorm2d num_features: 32
        relu
        
        flatten
        linear    dims:         ->15
    init:
        type: 'torch.nn.init.kaiming_normal_'
        conf: {'conv': {'mode': 'fan_out'}, 'linear': {'mode': 'fan_in'}}


training:
    B: 32
    log_interval: 20
    patience: 18
    optim: 'torch.optim.AdamW'
    opt: {}
    lr: 41e-4 
    decay_lr: 0.05


data:
    transformations:
        base:
            -   types:  torchvision.transforms.Resize
                params: {'size': [64, 64]}
        train:
            -   types:  torchvision.transforms.RandomHorizontalFlip
                params: {p: 0.5}
        normalization:
            -   types:  dataset.transformations.ChannelMean
                params: {}